# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

workspace 'twjcmobile'

target 'twjcmobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for twjcmobile
  # Required by RNFirebasegit status
  pod 'Firebase/Core', '~> 5.3.0'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  pod 'Firebase/Auth', '~> 5.3.0'
  pod 'Firebase/Database', '~> 5.3.0'
  pod 'Firebase/Performance', '~> 5.3.0'
  pod 'Firebase/Messaging', '~> 5.3.0'
  #pod 'Firebase/Analytics', '~> 5.3.0'
  #pod 'Firebase/AdMob', '~> 5.3.0'
  #pod 'Firebase/DynamicLinks', '~> 5.3.0'
  #pod 'Firebase/Firestore', '~> 5.3.0'
  #pod 'Firebase/RemoteConfig', '~> 5.3.0'
  #pod 'Firebase/Storage', '~> 5.3.0'
  


end
